apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mcsp-tenants
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - customer: customer-a
          - customer: customer-b
          - customer: customer-c
          - customer: customer-d
  template:
    metadata:
      name: 'mcsp-{{customer}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/VARSHITHA-P123/mcsp-hello-world.git
        targetRevision: main
        path: tenant-config/helm
        helm:
          parameters:
            - name: customerName
              value: '{{customer}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{customer}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true