apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mcsp-tenants
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/VARSHITHA-P123/mcsp-hello-world.git
        revision: main
        files:
          - path: "customers/*.yaml"
  template:
    metadata:
      name: 'mcsp-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/VARSHITHA-P123/mcsp-hello-world.git
        targetRevision: main
        path: tenant-config/customer-template
      destination:
        server: https://kubernetes.default.svc
        namespace: 'customer-a'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true