apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: customer-namespace-policy
  namespace: learning-workspace
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: pepsi-namespace
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: pepsi
                  labels:
                    tenant: pepsi
                    customer: "true"
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: pepsi-quota
                  namespace: pepsi
                spec:
                  hard:
                    requests.cpu: "1"
                    requests.memory: 512Mi
                    limits.cpu: "2"
                    limits.memory: 1Gi
                    pods: "10"
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: argocd-admin-pepsi
                  namespace: pepsi
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: pepsi-image-puller
                  namespace: learning-workspace
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: system:image-puller
                subjects:
                  - kind: ServiceAccount
                    name: default
                    namespace: pepsi
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cocacola-namespace
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: cocacola
                  labels:
                    tenant: cocacola
                    customer: "true"
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: cocacola-quota
                  namespace: cocacola
                spec:
                  hard:
                    requests.cpu: "1"
                    requests.memory: 512Mi
                    limits.cpu: "2"
                    limits.memory: 1Gi
                    pods: "10"
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: argocd-admin-cocacola
                  namespace: cocacola
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: cocacola-image-puller
                  namespace: learning-workspace
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: system:image-puller
                subjects:
                  - kind: ServiceAccount
                    name: default
                    namespace: cocacola
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: customer-namespace-policy-binding
  namespace: learning-workspace
placementRef:
  name: mcsp-hello-world-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: customer-namespace-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy