apiVersion: v1
kind: Secret
metadata:
  name: customer-a-source-secret
  namespace: learning-workspace
type: Opaque
stringData:
  customerName: "Customer A"
  apiKey: "customer-a-api-key-12345"
  dbPassword: "customer-a-db-pass-secure"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: learning-workspace
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: learning-workspace
      auth:
        serviceAccount:
          name: pipeline
          namespace: learning-workspace
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-b-source-secret
  namespace: learning-workspace
type: Opaque
stringData:
  customerName: "Customer B"
  apiKey: "customer-b-api-key-12345"
  dbPassword: "customer-b-db-pass-secure"
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-c-source-secret
  namespace: learning-workspace
type: Opaque
stringData:
  customerName: "Customer C"
  apiKey: "customer-c-api-key-12345"
  dbPassword: "customer-c-db-pass-secure"
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-d-source-secret
  namespace: learning-workspace
type: Opaque
stringData:
  customerName: "Customer D"
  apiKey: "customer-d-api-key-12345"
  dbPassword: "customer-d-db-pass-secure"
