apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.customerName }}-secrets
  namespace: {{ .Values.customerName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.customerName }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: customerName
      remoteRef:
        key: {{ .Values.customerName }}-source-secret
        property: customerName
    - secretKey: apiKey
      remoteRef:
        key: {{ .Values.customerName }}-source-secret
        property: apiKey
    - secretKey: dbPassword
      remoteRef:
        key: {{ .Values.customerName }}-source-secret
        property: dbPassword