apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcsp-app
  namespace: {{ .Values.customerName }}
  labels:
    app: mcsp-app
    tenant: {{ .Values.customerName }}
spec:
  to:
    kind: Service
    name: mcsp-app
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect