apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: learning-workspace
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: source
  steps:
    - name: clone
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      script: |
        #!/bin/sh
        set -e
        git config --global --add safe.directory $(workspaces.source.path)
        cd $(workspaces.source.path)
        git clone $(params.url) .
        git checkout $(params.revision)
        echo "=== Cloned contents ==="
        ls $(workspaces.source.path)