apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mcsp-build-pipeline
  namespace: learning-workspace
spec:
  params:
    - name: GIT_REVISION
      type: string
      default: main
  tasks:
    - name: run-tests
      taskRef:
        name: test-app
    - name: build-image
      taskRef:
        name: openshift-build
      runAfter:
        - run-tests
    - name: sync-argocd
      runAfter:
        - build-image
      taskRef:
        name: argocd-sync-check