apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mcsp-build-run-
  namespace: learning-workspace
spec:
  pipelineRef:
    name: mcsp-build-pipeline
  serviceAccountName: pipeline