apiVersion: v1
kind: Service
metadata:
  name: mcsp-app
  namespace: cocacola
  labels:
    app: mcsp-app
    tenant: cocacola
spec:
  selector:
    app: mcsp-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP