apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pepsi-tls
  namespace: pepsi
spec:
  secretName: pepsi-tls
  issuerRef:
    name: mcsp-selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - mcsp-app-pepsi.apps.zps-mcsp1.cp.fyre.ibm.com
  duration: 2160h
  renewBefore: 360h