apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: customer-b-secrets
  namespace: customer-b
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: customer-b-secrets
    creationPolicy: Owner
  data:
    - secretKey: customerName
      remoteRef:
        key: customer-b-source-secret
        property: customerName
    - secretKey: apiKey
      remoteRef:
        key: customer-b-source-secret
        property: apiKey
    - secretKey: dbPassword
      remoteRef:
        key: customer-b-source-secret
        property: dbPassword